# Generated by Django 5.1.6 on 2025-02-20 11:18

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("user_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
